id: P3B11B93A
initial_creation_type: ocr
source_metadata:
  volumes:
    981c402a5c8f4ae2a2f8e81397868400:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: མཉམ་ཉིད་གཞིའི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
